import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "zh";

export const translations = {
  en: {
    // Sidebar / Nav
    appName: "Price Intel",
    appBy: "BY NAVOS",
    nav: {
      dashboard: "Dashboard",
      products: "Products",
      history: "Price History",
      competitors: "Competitor Shops",
      alerts: "Alerts",
      recommendations: "Recommendations",
    },
    guestLabel: "Guest",
    demoMode: "Demo mode",
    signIn: "Sign in",
    signOut: "Sign out",

    // Layout / chrome
    layoutToggleNav: "Toggle navigation",
    layoutSwitchLangToZh: "Switch to Chinese",
    layoutSwitchLangToEn: "Switch to English",
    layoutThemeLight: "Switch to light mode",
    layoutThemeDark: "Switch to dark mode",
    layoutMenu: "Menu",

    // Dashboard
    dashboardTitle: "Price Dashboard",
    dashboardSubtitle: "Unified cross-platform price intelligence — live market view",
    refresh: "Refresh",
    trackedProducts: "Tracked Products",
    acrossAllPlatforms: "across all platforms",
    priceDrops: "Price Drops",
    priceRises: "Price Rises",
    sinceLastPoll: "since last poll",
    avgLandedPrice: "Avg Landed Price",
    allPlatforms: "all platforms",
    searchPlaceholder: "Search products, platforms, categories...",
    myProduct: "MY PRODUCT",
    poll: "Poll",
    current: "CURRENT",
    shipping: "SHIPPING",
    landed: "LANDED",
    lowest: "LOWEST",
    freeShipping: "Free",
    noProducts: "No products tracked yet",
    addFirstProduct: "Add your first product to start monitoring prices",
    addProduct: "Add Product",
    loadingStatsAria: "Loading dashboard statistics",
    marketInsightTitle: "Market insight",
    marketLargestDrop: "Largest drop",
    marketLargestRise: "Largest rise",
    marketDataFreshness: "Data freshness",
    marketNoDrop: "No drop detected",
    marketNoRise: "No rise detected",
    marketNoData: "No data",
    fetchPrice: "Fetch price",
    guestUnlockTitle: "Login to unlock full data and actions",
    guestUnlockSubtitle: "You are viewing a preview of 20 products.",
    pollingToast: (n: number) => `Polling ${n} product${n !== 1 ? "s" : ""}…`,
    alertsTriggeredToast: (n: number) => `${n} price alert${n !== 1 ? "s" : ""} triggered`,
    retry: "Retry",
    loggedInToast: "Logged in",
    loginFailedPrefix: "Login failed: ",
    pollingInProgress: "Polling…",

    // Feedback widget
    feedbackOpenAria: "Open feedback form",
    feedbackTitle: "Send feedback",
    feedbackDescription: "Tell us about bugs, feature requests, or any suggestions.",
    feedbackCatGeneral: "General",
    feedbackCatFeature: "Feature",
    feedbackCatBug: "Bug",
    feedbackPlaceholder: "Share your feedback…",
    feedbackSubmit: "Submit feedback",
    feedbackSubmitting: "Submitting…",
    feedbackSuccessToast: "Feedback submitted successfully.",
    feedbackFailedPrefix: "Submit failed: ",

    // Competitor shops page
    competitorsSubtitle: "Sellers discovered from tracked product snapshots.",
    competitorsLoading: "Loading competitor stores…",
    competitorsEmpty: "No competitor shops yet. Add products or store URLs in the AI agent.",
    competitorsTrackedCount: (n: number) => `${n} tracked product${n !== 1 ? "s" : ""}`,
    competitorsAvgLanded: "Avg landed",

    // Products toasts / validation
    toastProductExists: "Product already exists. Reusing existing entry.",
    toastProductAdded: "Product added and initial price fetched.",
    toastProductRemoved: "Product removed",
    toastProductRemoveFailed: "Failed to remove product",
    toastPasteAmazonUrl: "Please paste an Amazon product link.",

    // Products
    productsTitle: "Product Tracking",
    productsSubtitle: "Manage the products and competitors you monitor across platforms",
    newProduct: "New Product",
    removeProduct: "Remove",
    confirmRemove: "Remove this product from tracking?",
    cancel: "Cancel",
    confirm: "Confirm",
    platform: "Platform",
    productName: "Product Name",
    productId: "Product ID / SKU",
    productUrl: "Product URL (optional)",
    category: "Category",
    isOwnProduct: "This is my product",
    isOwnProductDesc: "Mark as your own product to get pricing recommendations",
    adding: "Adding…",
    add: "Add",
    noTrackedProducts: "No products tracked yet",
    addFirstProductHint: "Add products to start monitoring competitor prices",
    productIdPlaceholder: "e.g. B08N5WRWNW",
    categoryPlaceholder: "e.g. Electronics",
    namePlaceholder: "e.g. Wireless Headphones",
    urlPlaceholder: "https://...",
    selectPlatform: "Select platform",
    addProductTitle: "Add Tracked Product",
    addProductDesc: "Enter the product details to start monitoring its price across platforms.",
    removeProductTitle: "Remove Product",
    removeProductDesc: (name: string) => `Remove "${name}" from tracking? This will also delete all price history and alerts for this product.`,
    removing: "Removing…",
    remove: "Remove",
    trackedCount: (n: number) => `${n} product${n !== 1 ? "s" : ""} tracked`,

    // Price History
    historyTitle: "Price History",
    historySubtitle: "Historical price trends and volatility analysis",
    selectProduct: "Select a product",
    landedPrice: "Landed Price",
    listPrice: "List Price",
    overPeriod: "over period",
    noHistory: "No price history available. Select a product to view trends.",
    days: (n: number) => `${n} days`,

    // Alerts
    alertsTitle: "Price Alerts",
    alertsSubtitle: "Configure thresholds and review triggered price change notifications",
    newAlertRule: "New Alert Rule",
    alertLog: "Alert Log",
    rules: "Rules",
    unread: (n: number) => `${n} unread`,
    markAllRead: "Mark all read",
    noAlerts: "No alerts triggered yet",
    noRules: "No alert rules configured",
    createRule: "Create Alert Rule",
    createRuleDesc: "Get notified when a tracked product's price changes beyond your threshold.",
    product: "Product",
    selectProductPlaceholder: "Select a product",
    threshold: "Threshold (%)",
    thresholdHint: "Alert when price changes by at least this percentage",
    direction: "Direction",
    directionAny: "Any direction",
    directionUp: "Price increase only",
    directionDown: "Price decrease only",
    creating: "Creating…",
    createRuleBtn: "Create Rule",
    thresholdLabel: (pct: number) => `Threshold: ${pct}%`,
    directionLabel: (d: string) => `Direction: ${d}`,
    ruleCreated: "Alert rule created",
    ruleDeleted: "Alert rule deleted",
    allMarkedRead: "All alerts marked as read",
    pleaseSelectProduct: "Please select a product",
    thresholdMustBePositive: "Threshold must be a positive number",
    failedPrefix: "Failed: ",

    // Recommendations
    recsTitle: "Pricing Recommendations",
    recsSubtitle: "AI-powered optimal price suggestions based on market data and your margin rules",
    marginRules: "Margin Rules",
    configure: "Configure",
    saving: "Saving…",
    saveRules: "Save Rules",
    cogsPerUnit: "Cost of Goods (per unit)",
    platformFee: "Platform Fee (%)",
    shippingCost: "Shipping Cost (per unit)",
    minMargin: "Minimum Margin",
    targetMargin: "Target Margin",
    cogsLabel: "COGS / Unit",
    platformFeeLabel: "Platform Fee",
    shippingLabel: "Shipping Cost",
    minMarginLabel: "Min Margin",
    targetMarginLabel: "Target Margin",
    suggestedPricesTitle: "Suggested Prices for Your Products",
    noRecs: "No recommendations yet",
    noRecsHint: 'Mark products as "My Product" to get pricing suggestions',
    lowestLanded: "Lowest Landed",
    avgMarket: "Avg Market",
    minPriceFloor: "Min Price Floor",
    targetPrice: "Target Price",
    suggestedPrice: "Suggested Price",
    competitivePositioning: "Competitive positioning: 2% below lowest competitor",
    estMargin: "Est. Margin",
    aboveMin: "Above minimum threshold",
    belowMin: "Below minimum threshold",
    floor: "Floor",
    suggested: "Suggested",
    target: "Target",
    marginUpdated: "Margin rules updated",
    updateFailed: "Failed: ",
    targetMustBeHigher: "Target margin must be higher than minimum margin",

    // Chat
    chatPlaceholder: "Ask anything about your prices...",
    chatVoiceHint: "Voice input (coming soon)",
    chatNewConvo: "New conversation",
    chatSend: "Send",
    chatClear: "Clear",
    chatLiveData: "Live data",
    chatError: "Failed to get response. Please try again.",
    close: "Close",
    chatPanelTitle: "Price Intel AI",
    chatProactiveCta: "Ask AI about prices and trends",
    chatOpenQuickActionsAria: "Open agent quick actions",
    chatErrorNetwork: "Network issue",
    chatErrorServer: "Server error",
    chatRetry: "Retry",
    chatThinkingAria: "Thinking",
    chatAgentInputAria: "Agent input",
    chatTrackUrlChip: "Track this Amazon URL:",
    chatCompareLandedChip: "Compare lowest landed prices today",
    chatDropsChip: "Which products dropped the most today?",
    chatMovementChip: "Any price movement today?",
    chatShowTrendFor: (name: string) => `Show trend for ${name}`,
    trackedAddedSystem: (name: string) =>
      `✓ Added **${name}** to tracking. [View Products →](/products)`,
    productDefaultName: "Product",
    chatSuggestedPrompts: [
      "Which product has the biggest price drop?",
      "Where am I priced above market average?",
      "What's the best price for my product on Amazon?",
      "Which competitor has the lowest landed price?",
    ],

    documentTitle: "Price Intel — Price intelligence",
    appLoading: "Loading…",
    notFoundCode: "404",
    notFoundTitle: "Page not found",
    notFoundDescription:
      "Sorry, the page you are looking for doesn't exist. It may have been moved or deleted.",
    notFoundGoHome: "Go home",
    errorBoundaryTitle: "An unexpected error occurred.",
    errorBoundaryReload: "Reload page",
    manusLoginPrompt: "Please sign in with Manus to continue.",
    manusLoginButton: "Sign in with Manus",
    manusDialogGraphicAlt: "Dialog illustration",
    productsAmazonUrlHelp:
      "Paste an Amazon product link and the system will auto-detect ASIN, fetch details, and start tracking.",
    productsAmazonUrlPlaceholder: "https://www.amazon.com/dp/B0XXXXXXXX",
    productsPlatformCount: (n: number) => `${n} platform${n !== 1 ? "s" : ""}`,
    directionShortAny: "Any",
    directionShortUp: "Up",
    directionShortDown: "Down",
    alertRuleSummary: (pct: number, dir: string) => `Threshold: ${pct}% · Direction: ${dir}`,
    priceStatMin: "Low",
    priceStatMax: "High",
    chartSubtitleLastDays: (days: number) => `Last ${days} days`,
    showcasePageTitle: "Shadcn/ui component showcase",
    showcaseSectionToast: "Toast",
    showcaseSectionAiChat: "AI ChatBox",
    showcaseSonnerLabel: "Sonner Toast",
    showcaseBtnSuccess: "Success",
    showcaseBtnError: "Error",
    showcaseBtnInfo: "Info",
    showcaseBtnWarning: "Warning",
    showcaseBtnLoading: "Loading",
    showcaseBtnPromise: "Promise",
    showcaseDialogToastTitle: "Submitted successfully",
    showcaseDialogToastDesc: (value: string) => `Input: ${value}`,
    showcaseToastSuccessTitle: "Operation successful",
    showcaseToastSuccessDesc: "Your changes have been saved",
    showcaseToastErrorTitle: "Operation failed",
    showcaseToastErrorDesc: "Cannot complete the operation. Please try again.",
    showcaseToastInfoTitle: "Information",
    showcaseToastInfoDesc: "This is an informational message.",
    showcaseToastWarningTitle: "Warning",
    showcaseToastWarningDesc: "Please note the impact of this operation.",
    showcaseToastLoadingTitle: "Loading",
    showcaseToastLoadingDesc: "Please wait",
    showcaseToastPromiseLoading: "Processing…",
    showcaseToastPromiseSuccess: "Processing complete",
    showcaseToastPromiseError: "Processing failed",

    showcaseTitleMain: "Shadcn/ui Component Library",
    showcaseSecTextColors: "Text Colors",
    showcaseSecColorCombo: "Color Combinations",
    showcaseSecButtons: "Buttons",
    showcaseSecFormInputs: "Form Inputs",
    showcaseSecDataDisplay: "Data Display",
    showcaseSecAlertUI: "Alerts",
    showcaseSecTabs: "Tabs",
    showcaseSecAccordion: "Accordion",
    showcaseSecCollapsible: "Collapsible",
    showcaseSecOverlays: "Overlays",
    showcaseSecMenus: "Menus",
    showcaseSecCalendar: "Calendar",
    showcaseSecCarousel: "Carousel",
    showcaseSecToggle: "Toggle",
    showcaseSecLayout: "Layout Components",
    showcaseSecResizable: "Resizable Panels",

    showcaseBtnDefault: "Default",
    showcaseBtnSecondary: "Secondary",
    showcaseBtnDestructive: "Destructive",
    showcaseBtnOutline: "Outline",
    showcaseBtnGhost: "Ghost",
    showcaseBtnLink: "Link",
    showcaseBtnSmall: "Small",
    showcaseBtnLarge: "Large",
    showcaseBtnSaveChanges: "Save changes",
    showcaseBtnSavePassword: "Save password",
    showcaseBtnOpenDialog: "Open Dialog",
    showcaseBtnSubmit: "Submit",
    showcaseBtnOpenSheet: "Open Sheet",
    showcaseBtnOpenDrawer: "Open Drawer",
    showcaseBtnCancel: "Cancel",
    showcaseBtnOpenPopover: "Open Popover",
    showcaseBtnHoverMe: "Hover me",
    showcaseBtnDropdownMenu: "Dropdown Menu",
    showcaseBtnRightClick: "Right Click Me",
    showcaseBtnHoverCard: "Hover Card",
    showcaseBtnMinusTen: "−10",
    showcaseBtnPlusTen: "+10",
    showcaseThemeToggleLightAria: "Switch to dark theme",
    showcaseThemeToggleDarkAria: "Switch to light theme",

    showcaseAiChatIntro1:
      "A ready-to-use chat interface component that integrates with the LLM system. Features markdown rendering, auto-scrolling, and loading states.",
    showcaseAiChatIntro2:
      "This is a demo with simulated responses. In a real app, you would connect it to a tRPC mutation.",
    showcaseAiChatPlaceholder: "Try sending a message…",
    showcaseAiChatEmptyState: "How can I help you today?",
    showcaseAiChatPrompts: [
      "What is React?",
      "Explain TypeScript",
      "How to use tRPC?",
      "Best practices for web development",
    ],

    homeExampleTitle: "Example page",
    homeExampleMarkdown: "Sample **markdown** block.",
    homeExampleButton: "Example button",
    aiChatPlaceholderDefault: "Type your message…",
    aiChatEmptyStateDefault: "Start a conversation with the assistant",
    aiChatSendAria: "Send message",
    feedbackCardTitle: "Feedback",
    feedbackCardLead: "Tell us what to improve in this MVP.",
    feedbackCardSubmit: "Send feedback",

    // Availability
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    limited: "Limited",
    unknown: "Unknown",

    // Platform labels
    platforms: {
      amazon: "Amazon",
      ebay: "eBay",
      shopify: "Shopify",
      etsy: "Etsy",
    },
  },

  zh: {
    // Sidebar / Nav
    appName: "价格情报",
    appBy: "BY NAVOS",
    nav: {
      dashboard: "价格看板",
      products: "商品管理",
      history: "价格走势",
      competitors: "竞品店铺",
      alerts: "价格预警",
      recommendations: "定价建议",
    },
    guestLabel: "访客",
    demoMode: "演示模式",
    signIn: "登录",
    signOut: "退出登录",

    // Layout / chrome
    layoutToggleNav: "展开或收起导航",
    layoutSwitchLangToZh: "切换到中文",
    layoutSwitchLangToEn: "切换到 English",
    layoutThemeLight: "切换到浅色模式",
    layoutThemeDark: "切换到深色模式",
    layoutMenu: "菜单",

    // Dashboard
    dashboardTitle: "价格看板",
    dashboardSubtitle: "跨平台价格情报 — 实时市场视图",
    refresh: "刷新",
    trackedProducts: "追踪商品",
    acrossAllPlatforms: "覆盖所有平台",
    priceDrops: "价格下降",
    priceRises: "价格上涨",
    sinceLastPoll: "较上次轮询",
    avgLandedPrice: "平均到手价",
    allPlatforms: "全平台",
    searchPlaceholder: "搜索商品、平台、分类…",
    myProduct: "我的商品",
    poll: "轮询",
    current: "当前价",
    shipping: "运费",
    landed: "到手价",
    lowest: "最低",
    freeShipping: "免运费",
    noProducts: "暂无追踪商品",
    addFirstProduct: "添加第一个商品以开始监控价格",
    addProduct: "添加商品",
    loadingStatsAria: "正在加载看板统计",
    marketInsightTitle: "市场洞察",
    marketLargestDrop: "最大跌幅",
    marketLargestRise: "最大涨幅",
    marketDataFreshness: "数据新鲜度",
    marketNoDrop: "暂无下跌",
    marketNoRise: "暂无上涨",
    marketNoData: "暂无数据",
    fetchPrice: "获取价格",
    guestUnlockTitle: "登录以解锁完整数据与操作",
    guestUnlockSubtitle: "当前为演示模式，仅展示 20 条商品预览。",
    pollingToast: (n: number) => `正在轮询 ${n} 个商品…`,
    alertsTriggeredToast: (n: number) => `已触发 ${n} 条价格预警`,
    retry: "重试",
    loggedInToast: "已登录",
    loginFailedPrefix: "登录失败：",
    pollingInProgress: "轮询中…",

    // Feedback widget
    feedbackOpenAria: "打开反馈表单",
    feedbackTitle: "发送反馈",
    feedbackDescription: "欢迎反馈缺陷、功能建议或其他想法。",
    feedbackCatGeneral: "一般",
    feedbackCatFeature: "功能建议",
    feedbackCatBug: "缺陷",
    feedbackPlaceholder: "请描述你的反馈…",
    feedbackSubmit: "提交反馈",
    feedbackSubmitting: "提交中…",
    feedbackSuccessToast: "反馈已提交。",
    feedbackFailedPrefix: "提交失败：",

    // Competitor shops page
    competitorsSubtitle: "来自已追踪商品价格快照的卖家信息。",
    competitorsLoading: "正在加载竞品店铺…",
    competitorsEmpty: "暂无竞品店铺。请在 AI 助手中添加商品或店铺链接。",
    competitorsTrackedCount: (n: number) => `已追踪 ${n} 个商品`,
    competitorsAvgLanded: "平均到手",

    // Products toasts / validation
    toastProductExists: "该商品已存在，已定位到现有记录",
    toastProductAdded: "商品已添加并完成首次价格抓取",
    toastProductRemoved: "商品已移除",
    toastProductRemoveFailed: "移除失败",
    toastPasteAmazonUrl: "请先粘贴 Amazon 商品链接",

    // Products
    productsTitle: "商品追踪",
    productsSubtitle: "管理跨平台监控的商品和竞争对手",
    newProduct: "新增商品",
    removeProduct: "移除",
    confirmRemove: "确认移除此商品的追踪？",
    cancel: "取消",
    confirm: "确认",
    platform: "平台",
    productName: "商品名称",
    productId: "商品 ID / SKU",
    productUrl: "商品链接（可选）",
    category: "分类",
    isOwnProduct: "这是我的商品",
    isOwnProductDesc: "标记为自有商品以获取定价建议",
    adding: "添加中…",
    add: "添加",
    noTrackedProducts: "暂无追踪商品",
    addFirstProductHint: "添加商品以开始监控竞争对手价格",
    productIdPlaceholder: "例如 B08N5WRWNW",
    categoryPlaceholder: "例如 电子产品",
    namePlaceholder: "例如 无线耳机",
    urlPlaceholder: "https://...",
    selectPlatform: "选择平台",
    addProductTitle: "添加追踪商品",
    addProductDesc: "输入商品信息，开始跨平台监控价格。",
    removeProductTitle: "移除商品",
    removeProductDesc: (name: string) => `移除"${name}"的追踪？此操作将同时删除该商品的所有价格历史和预警记录。`,
    removing: "移除中…",
    remove: "移除",
    trackedCount: (n: number) => `已追踪 ${n} 个商品`,

    // Price History
    historyTitle: "价格走势",
    historySubtitle: "历史价格走势与波动分析",
    selectProduct: "选择商品",
    landedPrice: "到手价",
    listPrice: "列表价",
    overPeriod: "周期内",
    noHistory: "暂无价格历史，请选择商品查看走势。",
    days: (n: number) => `${n} 天`,

    // Alerts
    alertsTitle: "价格预警",
    alertsSubtitle: "配置预警阈值，查看价格变动通知",
    newAlertRule: "新建预警规则",
    alertLog: "预警日志",
    rules: "规则",
    unread: (n: number) => `${n} 条未读`,
    markAllRead: "全部标记已读",
    noAlerts: "暂无触发的预警",
    noRules: "暂无预警规则",
    createRule: "创建预警规则",
    createRuleDesc: "当追踪商品价格变动超过设定阈值时，自动接收通知。",
    product: "商品",
    selectProductPlaceholder: "选择商品",
    threshold: "阈值 (%)",
    thresholdHint: "价格变动超过此百分比时触发预警",
    direction: "方向",
    directionAny: "任意方向",
    directionUp: "仅价格上涨",
    directionDown: "仅价格下降",
    creating: "创建中…",
    createRuleBtn: "创建规则",
    thresholdLabel: (pct: number) => `阈值：${pct}%`,
    directionLabel: (d: string) => d === "any" ? "任意" : d === "up" ? "上涨" : "下降",
    ruleCreated: "预警规则已创建",
    ruleDeleted: "预警规则已删除",
    allMarkedRead: "已全部标记为已读",
    pleaseSelectProduct: "请选择一个商品",
    thresholdMustBePositive: "阈值必须为正数",
    failedPrefix: "失败：",

    // Recommendations
    recsTitle: "定价建议",
    recsSubtitle: "基于市场数据和利润规则的 AI 最优定价建议",
    marginRules: "利润规则",
    configure: "配置",
    saving: "保存中…",
    saveRules: "保存规则",
    cogsPerUnit: "商品成本（单件）",
    platformFee: "平台佣金 (%)",
    shippingCost: "头程运费（单件）",
    minMargin: "最低利润率",
    targetMargin: "目标利润率",
    cogsLabel: "商品成本",
    platformFeeLabel: "平台佣金",
    shippingLabel: "头程运费",
    minMarginLabel: "最低利润率",
    targetMarginLabel: "目标利润率",
    suggestedPricesTitle: "你的商品定价建议",
    noRecs: "暂无建议",
    noRecsHint: "将商品标记为\"我的商品\"以获取定价建议",
    lowestLanded: "最低到手价",
    avgMarket: "市场均价",
    minPriceFloor: "最低定价底线",
    targetPrice: "目标定价",
    suggestedPrice: "建议定价",
    competitivePositioning: "竞争定位：比最低竞争对手低 2%",
    estMargin: "预估利润率",
    aboveMin: "高于最低阈值",
    belowMin: "低于最低阈值",
    floor: "底线",
    suggested: "建议",
    target: "目标",
    marginUpdated: "利润规则已更新",
    updateFailed: "更新失败：",
    targetMustBeHigher: "目标利润率必须高于最低利润率",

    // Chat
    chatPlaceholder: "询问任何关于价格的问题…",
    chatVoiceHint: "语音输入（即将推出）",
    chatNewConvo: "新对话",
    chatSend: "发送",
    chatClear: "清空",
    chatLiveData: "实时数据",
    chatError: "无法生成回答，请重试。",
    close: "关闭",
    chatPanelTitle: "价格情报 AI",
    chatProactiveCta: "向 AI 询问价格与趋势",
    chatOpenQuickActionsAria: "打开智能助手快捷操作",
    chatErrorNetwork: "网络问题",
    chatErrorServer: "服务器错误",
    chatRetry: "重试",
    chatThinkingAria: "思考中",
    chatAgentInputAria: "智能助手输入框",
    chatTrackUrlChip: "追踪这个 Amazon 链接：",
    chatCompareLandedChip: "对比今日最低到手价",
    chatDropsChip: "今天哪些商品跌幅最大？",
    chatMovementChip: "今天有没有价格波动？",
    chatShowTrendFor: (name: string) => `展示「${name}」的价格走势`,
    trackedAddedSystem: (name: string) =>
      `✓ 已将 **${name}** 加入追踪。[前往商品列表 →](/products)`,
    productDefaultName: "商品",
    chatSuggestedPrompts: [
      "哪个商品的价格降幅最大？",
      "我的哪些商品定价高于市场均价？",
      "我在亚马逊的商品最佳定价是多少？",
      "哪个竞争对手的到手价最低？",
    ],

    documentTitle: "价格情报 — 跨平台价格监控",
    appLoading: "加载中…",
    notFoundCode: "404",
    notFoundTitle: "页面未找到",
    notFoundDescription: "抱歉，你访问的页面不存在，或已被移动、删除。",
    notFoundGoHome: "返回首页",
    errorBoundaryTitle: "发生了意外错误。",
    errorBoundaryReload: "重新加载页面",
    manusLoginPrompt: "请使用 Manus 登录以继续。",
    manusLoginButton: "使用 Manus 登录",
    manusDialogGraphicAlt: "对话框配图",
    productsAmazonUrlHelp: "粘贴 Amazon 商品链接，系统会自动识别 ASIN、抓取商品信息并加入监控。",
    productsAmazonUrlPlaceholder: "https://www.amazon.com/dp/B0XXXXXXXX",
    productsPlatformCount: (n: number) => `${n} 个平台`,
    directionShortAny: "任意",
    directionShortUp: "涨",
    directionShortDown: "跌",
    alertRuleSummary: (pct: number, dir: string) => `阈值：${pct}% · 方向：${dir}`,
    priceStatMin: "最低",
    priceStatMax: "最高",
    chartSubtitleLastDays: (days: number) => `最近 ${days} 天`,
    showcasePageTitle: "Shadcn/ui 组件展示",
    showcaseSectionToast: "Toast 提示",
    showcaseSectionAiChat: "AI 对话框",
    showcaseSonnerLabel: "Sonner Toast",
    showcaseBtnSuccess: "成功",
    showcaseBtnError: "错误",
    showcaseBtnInfo: "信息",
    showcaseBtnWarning: "警告",
    showcaseBtnLoading: "加载中",
    showcaseBtnPromise: "Promise",
    showcaseDialogToastTitle: "提交成功",
    showcaseDialogToastDesc: (value: string) => `输入内容：${value}`,
    showcaseToastSuccessTitle: "操作成功",
    showcaseToastSuccessDesc: "更改已保存",
    showcaseToastErrorTitle: "操作失败",
    showcaseToastErrorDesc: "无法完成操作，请重试。",
    showcaseToastInfoTitle: "提示",
    showcaseToastInfoDesc: "这是一条信息提示。",
    showcaseToastWarningTitle: "警告",
    showcaseToastWarningDesc: "请注意此操作的影响。",
    showcaseToastLoadingTitle: "加载中",
    showcaseToastLoadingDesc: "请稍候",
    showcaseToastPromiseLoading: "处理中…",
    showcaseToastPromiseSuccess: "处理完成",
    showcaseToastPromiseError: "处理失败",

    showcaseTitleMain: "Shadcn/ui 组件库",
    showcaseSecTextColors: "文字颜色",
    showcaseSecColorCombo: "颜色组合",
    showcaseSecButtons: "按钮",
    showcaseSecFormInputs: "表单输入",
    showcaseSecDataDisplay: "数据展示",
    showcaseSecAlertUI: "提示框",
    showcaseSecTabs: "标签页",
    showcaseSecAccordion: "手风琴",
    showcaseSecCollapsible: "可折叠",
    showcaseSecOverlays: "浮层",
    showcaseSecMenus: "菜单",
    showcaseSecCalendar: "日历",
    showcaseSecCarousel: "轮播",
    showcaseSecToggle: "开关",
    showcaseSecLayout: "布局组件",
    showcaseSecResizable: "可调整面板",

    showcaseBtnDefault: "默认",
    showcaseBtnSecondary: "次要",
    showcaseBtnDestructive: "危险",
    showcaseBtnOutline: "描边",
    showcaseBtnGhost: "幽灵",
    showcaseBtnLink: "链接",
    showcaseBtnSmall: "小",
    showcaseBtnLarge: "大",
    showcaseBtnSaveChanges: "保存更改",
    showcaseBtnSavePassword: "保存密码",
    showcaseBtnOpenDialog: "打开对话框",
    showcaseBtnSubmit: "提交",
    showcaseBtnOpenSheet: "打开侧边栏",
    showcaseBtnOpenDrawer: "打开抽屉",
    showcaseBtnCancel: "取消",
    showcaseBtnOpenPopover: "打开气泡",
    showcaseBtnHoverMe: "悬停我",
    showcaseBtnDropdownMenu: "下拉菜单",
    showcaseBtnRightClick: "右键我",
    showcaseBtnHoverCard: "悬停卡片",
    showcaseBtnMinusTen: "−10",
    showcaseBtnPlusTen: "+10",
    showcaseThemeToggleLightAria: "切换到深色主题",
    showcaseThemeToggleDarkAria: "切换到浅色主题",

    showcaseAiChatIntro1:
      "可与 LLM 系统对接的现成聊天界面组件，支持 Markdown 渲染、自动滚动与加载状态。",
    showcaseAiChatIntro2: "当前为模拟回复演示；在真实应用中可接入 tRPC mutation。",
    showcaseAiChatPlaceholder: "试着发送一条消息…",
    showcaseAiChatEmptyState: "今天我能帮你什么？",
    showcaseAiChatPrompts: ["什么是 React？", "解释 TypeScript", "如何使用 tRPC？", "Web 开发最佳实践"],

    homeExampleTitle: "示例页面",
    homeExampleMarkdown: "示例 **Markdown** 内容。",
    homeExampleButton: "示例按钮",
    aiChatPlaceholderDefault: "输入消息…",
    aiChatEmptyStateDefault: "开始与助手对话",
    aiChatSendAria: "发送消息",
    feedbackCardTitle: "反馈",
    feedbackCardLead: "告诉我们这个 MVP 需要改进的地方。",
    feedbackCardSubmit: "发送反馈",

    // Availability
    inStock: "有货",
    outOfStock: "缺货",
    limited: "库存紧张",
    unknown: "未知",

    // Platform labels
    platforms: {
      amazon: "亚马逊",
      ebay: "eBay",
      shopify: "Shopify",
      etsy: "Etsy",
    },
  },
} as const;

// Use a structural type that works for both languages
export type Translations = {
  [K in keyof typeof translations.en]: (typeof translations.en)[K] extends (...args: infer A) => infer R
    ? (...args: A) => R
    : (typeof translations.en)[K] extends readonly string[]
    ? readonly string[]
    : string;
};

type LanguageContextType = {
  lang: Lang;
  t: (typeof translations)[Lang];
  toggleLang: () => void;
};

const LanguageContext = createContext<LanguageContextType | null>(null);

function readStoredLang(): Lang | null {
  try {
    const saved = localStorage.getItem("price-intel-lang");
    return saved === "zh" || saved === "en" ? saved : null;
  } catch {
    return null;
  }
}

function detectBrowserLang(): Lang {
  if (typeof navigator === "undefined") return "en";
  return navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";
}

/** Active UI language (localStorage override, else browser). Safe outside React for class components. */
export function readActiveLang(): Lang {
  return readStoredLang() ?? detectBrowserLang();
}

/** Translation bundle for a given language (e.g. ErrorBoundary). */
export function tAt(lang: Lang): (typeof translations)["en"] {
  return translations[lang] as (typeof translations)["en"];
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => readActiveLang());

  useEffect(() => {
    try {
      localStorage.setItem("price-intel-lang", lang);
    } catch {}
  }, [lang]);

  useEffect(() => {
    if (typeof document === "undefined") return;
    document.documentElement.lang = lang === "zh" ? "zh-Hans" : "en";
    document.title = translations[lang].documentTitle;
  }, [lang]);

  const toggleLang = () => setLang((l) => (l === "en" ? "zh" : "en"));

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used inside LanguageProvider");
  return ctx;
}
